artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1ugZsVw03YafQMvPi7J6E7rD6Tq6jhizz/view?usp=sharing
  local_data_file: artifacts/data_ingestion/solar_dust_detection.zip
  unzipped_data_dir: artifacts/data_ingestion



base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.pt
  updated_base_model_path: artifacts/base_model/updated_base_model.pt



training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pt
